### PR TITLE
Fixed condition in ligatures

### PR DESCRIPTION
**Pull request by CsBigDataHub**
if emacs version<=27.0 we need to define the char sets to apply font-ligatures
but with emacs>=27.1, HarfBuzz support is added and emacs can support
font ligatures from out of the box.

### CODE REVIEW

**Comment by seagle0128** [comment]
The check is correct, why creat this pr?

**Comment by seagle0128** [comment]
The check is correct, why creat this pr?

**Comment by CsBigDataHub** [comment]
Unless until I made this change font ligatures were not activated.

**Comment by seagle0128** [comment]
> Unless until I made this change font ligatures were not activated.

Which version are you using? Or try `(< emacs-major-version 27)`?

**Comment by CsBigDataHub** [comment]
I am using 27.1

**Comment by seagle0128** [comment]
It doesn't make sense to me. The checking condition is same.

**Comment by CsBigDataHub** [comment]
> It doesn't make sense to me. The checking condition is same.

yep for whatever reason the condition does not work. I just build Emacs 27.1.50 on Ubuntu and tested this.

**Comment by seagle0128** [comment]
What is result of `(< emacs-major-version 27)` in your env?

**Comment by CsBigDataHub** [comment]
> What are results of `emacs/>=27p` and `(< emacs-major-version 27)` in your env?

`(unless (< emacs-major-version 27)`  - works - can see font-ligatures
`(when (version<= "27.0" emacs-version)` - works - can see font-ligatures
`(unless emacs/>=27p` - does not work - No font-ligatures

**Comment by seagle0128** [comment]
> `(unless (< emacs-major-version 27)` - works - can see font-ligatures
> `(when (version<= "27.0" emacs-version)` - works - can see font-ligatures
> `(unless emacs/>=27p` - does not work - No font-ligatures

Are you sure about it? It's not possible.

If using Emacs 27.1,
- `(unless (< emacs-major-version 27)` is t
- `(when (version<= "27.0" emacs-version)` is nil
- `(unless emacs/>=27p` is nil.

**Comment by CsBigDataHub** [comment]
> > `(unless (< emacs-major-version 27)` - works - can see font-ligatures
> > `(when (version<= "27.0" emacs-version)` - works - can see font-ligatures
> > `(unless emacs/>=27p` - does not work - No font-ligatures
> 
> Are you sure about it? It's not possible.
> 
> If using Emacs 27.1,
> 
> * `(unless (< emacs-major-version 27)` is t
> * `(when (version<= "27.0" emacs-version)` is nil
> * `(unless emacs/>=27p` is nil.

After each change I have re-started emacs for the font ligatures to take effect.

`(unless emacs/>=27p`

image

`(unless (< emacs-major-version 27)`
image

`(when (version<= "27.0" emacs-version)`
image

**Comment by seagle0128** [comment]
So the condition should be `(when emacs/>=27p)`, right?

BTW, what fonts are you using?

**Comment by CsBigDataHub** [comment]
> So the condition should be `(when emacs/>=27p)`, right?
Yes

> BTW, what fonts are you using?

https://github.com/JetBrains/JetBrainsMono

**Pull request closed without merging**
