### PR TITLE
Added support for org-reveal

### PR DESCRIPTION
**Pull request by kosantosbik**

### CODE REVIEW

**Comment by seagle0128** [comment]
Thank you!

**Comment by seagle0128** [comment]
Sorry! I decided to revert this PR, since some people reports there are some troubles to install the latest `org-mode`, or conflicts with their private configurations. It seems that `ox-reveal` is not good for everyone.

**Comment by kosantosbik** [comment]
Can you refer some error examples about it? I know of the problem people are facing and I believe I can fix it.

**Comment by seagle0128** [comment]
e.g. 
1. Some people from China are difficult to access `orgmode.org` directly.
1. Some people don't want to install the latest `org-mode`.
1. Some people don't use `org-reveal`, but have to install the huge `org-mode` package although it has been built-in. 
...

**Comment by seagle0128** [comment]
I check the codes of `org-reveal` today. Seems the `org` dependency should be removed, and add emacs 24.4 like other packages. You can file an issue there, but the project looks dead now...

**Pull request merged**
